<?php

namespace App\Repository;

/**
 * CasoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CasoRepository extends \Doctrine\ORM\EntityRepository
{
    public function filtroDQL($codigoClientePk = 0) {
        $dql   = "SELECT e, d FROM App:Caso d JOIN d.clienteRel e WHERE d.codigoClienteFk <> 0";
        if ($codigoClientePk <> 0){
           $dql .= " AND e.codigoClientePk =" . $codigoClientePk;
        }
        $dql .= " ORDER BY d.fechaRegistro ASC";

        return $dql;
    }

    public function listarPorEmpresa($codigoCliente){

	    $em = $this->getEntityManager();
	    $qb = $em->createQueryBuilder();
	    $qb->from("App:Caso", "c")
	       ->select("c.codigoCasoPk")
	       ->addSelect("c.asunto")
	       ->addSelect("c.codigoAreaFk")
	       ->addSelect("c.codigoCargoFk")
		   ->addSelect("c.codigoClienteFk")
		   ->addSelect("c.codigoPrioridadFk")
	       ->addSelect("c.codigoCategoriaCasoFk");
	    return $qb->getQuery()->getResult();
    }
}