<?php

namespace App\Repository;

use Doctrine\ORM\EntityManagerInterface;
use Doctrine\ORM\Mapping;

/**
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ImplementacionDetalleRepository extends \Doctrine\ORM\EntityRepository
{

  public function apiDetalle($codigoImplementacion)
  {
      $em = $this->getEntityManager();
      $qb = $em->createQueryBuilder()->from("App:ImplementacionDetalle", "id")
          ->select("id.codigoImplementacionDetallePk")
          ->addSelect("ig.nombre AS nombreGrupo")
          ->addSelect("it.nombre AS nombreTema")
          ->join("id.implementacionRel", "i")
          ->join("id.implementacionGrupoRel","ig")
          ->join("id.implementacionTemaRel","it")
          ->where("id.codigoImplementacionFK = {$codigoImplementacion}");
      return $qb->getQuery()->getResult();

  }

}
