<?php

namespace App\Repository;

/**
 * LlamadaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LlamadaRepository extends \Doctrine\ORM\EntityRepository
{    
    public function getPendientes() {
        $em = $this->getEntityManager();
        $pendientes = 0;
        $dql   = "SELECT COUNT(l.codigoLlamadaPk) AS pendientes FROM App:Llamada l WHERE l.estadoAtendido = 0 AND l.estadoSolucionado = 0";
        $query = $em->createQuery($dql);
        $arrLlamadas = $query->getSingleResult();
        if($arrLlamadas) {
            $pendientes = $arrLlamadas['pendientes'];
        }
        return $pendientes;
    }  
    
    public function getAtendidasPendientes() {
        $em = $this->getEntityManager();
        $atendidasPendientes = 0;
        $dql   = "SELECT COUNT(l.codigoLlamadaPk) AS atendidasPendientes FROM App:Llamada l WHERE l.estadoAtendido = 1 AND l.estadoSolucionado = 0";
        $query = $em->createQuery($dql);
        $arrLlamadas = $query->getSingleResult();
        if($arrLlamadas) {
            $atendidasPendientes = $arrLlamadas['atendidasPendientes'];
        }
        return $atendidasPendientes;
    }


    public function getAtendidasPendientesUsuario($codigoUsuarioAtiende)
    {
        $em = $this->getEntityManager();
        $atendidasPendientesusuario = 0;
        $dql = "SELECT COUNT(l.codigoLlamadaPk) AS atendidasPendientesUsuario FROM App:Llamada l WHERE l.estadoAtendido = 1 AND l.estadoSolucionado = 0 AND l.codigoUsuarioAtiendeFk = '" . $codigoUsuarioAtiende."'";
        $query = $em->createQuery($dql);
        $arrLlamadas = $query->getSingleResult();
        if ($arrLlamadas) {
            $atendidasPendientesUsuario = $arrLlamadas['atendidasPendientesUsuario'];
        }
        return $atendidasPendientesUsuario;
    }

    public function listaDql($codigoClientePk = "")
        {
            $em = $this->getEntityManager();
            $db = $em->createQueryBuilder()->from("App:Llamada", "l")
                ->select("l")
                ->andWhere("l.codigoLlamadaPk <> 0")
                ->orderBy("l.fechaRegistro","DESC");
//                ->orderBy("l.estadoAtendido", "ASC")
//                ->addOrderBy("l.estadoSolucionado", "ASC");
            if ($codigoClientePk != "") {
                $db->andWhere("l.codigoClienteFk = {$codigoClientePk}");
            }

            return $db;

        }

    public function tableroSinAtender() {
        $em = $this->getEntityManager();
        $arrSinAtender = array('numero' => 0, 'arrLlamadas' => array());
        $dql = "SELECT COUNT(l.codigoLlamadaPk) as numero FROM App:Llamada l "
            . "WHERE l.estadoAtendido = 0 ";
        $query = $em->createQuery($dql);
        $arrayResultado = $query->getResult();
        if ($arrayResultado) {
            $arrSinAtender['numero'] = $arrayResultado[0]['numero'];
        }
        $dql = "SELECT l.codigoLlamadaPk, l.fechaRegistro, cli.nombreComercial  FROM App:Llamada l JOIN l.clienteRel cli "
            . "WHERE l.estadoAtendido = 0 ORDER BY l.fechaRegistro";
        $query = $em->createQuery($dql);
        $query->setMaxResults(5);
        $arrayResultado = $query->getResult();
        if ($arrayResultado) {
            $arrSinAtender['arrLlamadas'] = $arrayResultado;
        }
        return $arrSinAtender;
    }

    public function tableroSinSolucionar() {
        $em = $this->getEntityManager();
        $arrSinSolucionar = array('numero' => 0, 'arrLlamadas' => array());
        $dql = "SELECT COUNT(l.codigoLlamadaPk) as numero FROM App:Llamada l "
            . "WHERE l.estadoAtendido = 1 AND l.estadoSolucionado = 0 ";
        $query = $em->createQuery($dql);
        $arrayResultado = $query->getResult();
        if ($arrayResultado) {
            $arrSinSolucionar['numero'] = $arrayResultado[0]['numero'];
        }
        $dql = "SELECT l.codigoLlamadaPk, l.fechaRegistro, cli.nombreComercial  FROM App:Llamada l JOIN l.clienteRel cli "
            . "WHERE l.estadoAtendido = 1 AND l.estadoSolucionado = 0 ORDER BY l.fechaRegistro";
        $query = $em->createQuery($dql);
        $query->setMaxResults(10);
        $arrayResultado = $query->getResult();
        if ($arrayResultado) {
            $arrSinSolucionar['arrLlamadas'] = $arrayResultado;
        }
        return $arrSinSolucionar;
    }
}
